---

services:
  - name: docker:20.10.2-dind
    alias: docker

variables:
  ANSIBLE_FORCE_COLOR: '1'
  DOCKER_HOST: tcp://docker:2375/
  PY_COLORS: '1'

before_script:
  - python3 --version
  - ansible --version
  - molecule --version
  - docker info

molecule-scenario-default:
  stage: test
  image: neonmei/ansible-toolset:2.10.5-3.2.2
  script:
    - molecule test
