---

variables:
  ANSIBLE_FORCE_COLOR: '1'
  PY_COLORS: '1'

# Not supported on per-job basis
# See issue: https://gitlab.com/gitlab-org/gitlab/-/issues/19561
services:
  - name: docker:20.10.2-dind
    alias: docker

before_script:
  - python3 --version
  - ansible --version
  - molecule --version
  - docker info

# Job name can't be  dynamically customized just yet
# See issue: https://gitlab.com/gitlab-org/gitlab/-/issues/27621
molecule-scenario-default:
  stage: test
  parallel:
    matrix:
      - TOOLSET_VERSION: 2.9.17-3.2.2
      - TOOLSET_VERSION: 2.10.5-3.2.2
  image: neonmei/ansible-toolset:$TOOLSET_VERSION
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - molecule test
