name: Molecule tests
on: [pull_request, workflow_dispatch, release, push]

jobs:
  molecule-default:
    runs-on: ubuntu-latest
    container: neonmei/ansible-toolset:2.10.5-3.2.2

    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
          with:
            path: ansible_role_yara

        - name: Launch default molecule scenario
          run: molecule test
