name: Molecule tests
on: [pull_request, workflow_dispatch, release, push]

jobs:
  molecule-scenario-default:
    runs-on: ubuntu-latest
    container: neonmei/ansible-toolset:${{ matrix.toolset_version }}
    strategy:
      matrix:
        # This corresponds to ansible_version-molecule_version
        toolset_version:
          - 2.9.17-3.2.2
          - 2.10.5-3.2.2
    name: Ansible-Molecule version ${{ matrix.toolset_version }}

    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
          with:
            path: ansible_role_yara

        - name: Launch default molecule scenario
          run: molecule test
          env:
            ANSIBLE_FORCE_COLOR: '1'
            PY_COLORS: '1'
